### PR TITLE
Use arrow functions where possible to help with minification

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
This should help reduce the size of the package by using implicit returns and allow minifiers to declare multiple constants with just one const keyword.

Example:
with functions:
```js
function one(){return "1"};
function two(){return "2"};
function three(){return "3"};
```
with arrow functions:
```js
const one=()=>"1", two=()=>"2", three=()=>"3";
```

### CODE REVIEW

**Comment by dcastil** [comment]
Hey @VIKTORVAV99! 👋

Thanks for your PR, I appreciate it a lot!

I'm not yet sure whether it would make sense to add this change. I assumed that minifiers already change them to arrow functions when possible to compress their size. But on the other hand I just checked Skypack ([source](https://cdn.skypack.dev/-/tailwind-merge@v2.4.0-SLvupcG2OtzkOsjfrv7s/dist=es2019,mode=imports,min/optimized/tailwind-merge.js)) and Bundlejs ([source](https://bundlejs.com/?q=tailwind-merge&treeshake=%5B*%5D)) and they indeed preserve the function declarations. 🤔

**Comment by dcastil** [comment]
Just checked the size report in https://github.com/dcastil/tailwind-merge/actions/runs/10058157215/job/27879795604?pr=449#step:9:33. In comparison to the last size report in https://github.com/dcastil/tailwind-merge/pull/444#issuecomment-2212489002 it looks like this reduces the size by around 0.4% uncompressed, 2.4% minified and 1.2% when miniifed and brotli-compressed.

Nothing too crazy, but looks like an improvement. Let's just do it then. 👍

**Review by dcastil — APPROVED** [review]
LGTM

**Comment by VIKTORVAV99** [comment]
Terser goes one step further than most other minifyers but I think this makes sense as plenty of people use Vite with ESBuild for example (like we do at Electricity Maps) since there is a big difference in performance. So I'm glad to see you think it makes sense as well!

**Comment by dcastil** [comment]
Yeah we also use Vite like many others at my work, so makes sense to go the extra mile. Thanks again for the PR!

By the way just compared the results:

Before: https://cdn.skypack.dev/tailwind-merge@2.4.0?min imports https://cdn.skypack.dev/-/tailwind-merge@v2.4.0-SLvupcG2OtzkOsjfrv7s/dist=es2019,mode=imports,min/optimized/tailwind-merge.js which is 21.5 kB minified. 51 `function` keywords, 62 `return` keywords.

After: https://cdn.skypack.dev/tailwind-merge@2.4.0-dev.38db48d362b45aab9ba7e2e05aef4c36abab6edb?min imports https://cdn.skypack.dev/-/tailwind-merge@v2.4.0-dev.38db48d362b45aab9ba7e2e05aef4c36abab6edb-8NJ5BgX8RdAs58xjlwlX/dist=es2019,mode=imports,min/optimized/tailwind-merge.js which is 21.0 kB minified. 7 `function` keywords, 40 `return` keywords.

**Comment by VIKTORVAV99** [comment]
A small reduction but considering how many people use your package the collective savings will be significant!

**Pull request merged**
